server {
    listen 8080;
    server_name localhost;

    root  /var/www/html/public;
    index index.php;

    client_max_body_size 50M;

    add_header X-Frame-Options        "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass   app:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include        fastcgi_params;
        fastcgi_read_timeout 60;
    }

    location ~ /\.(env|git|htaccess) { deny all; }

    error_log  /var/log/nginx/lyon_palme_error.log;
    access_log /var/log/nginx/lyon_palme_access.log;
}
